<a href="https://colab.research.google.com/github/thq4n/Learn-Colab/blob/main/DLGC_GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.cuda.is_available()


True

In [2]:
# memory footprint support libraries/code
!ln -sf /opt/bin/nvidia-smi /usr/bin/nvidia-smi
!pip install gputil
!pip install psutil
!pip install humanize
import psutil
import humanize
import os
import GPUtil as GPU
GPUs = GPU.getGPUs()
# XXX: only one GPU on Colab and isn’t guaranteed
gpu = GPUs[0]
def printm():
 process = psutil.Process(os.getpid())
 print("Gen RAM Free: " + humanize.naturalsize( psutil.virtual_memory().available ), " | Proc size: " + humanize.naturalsize( process.memory_info().rss))
 print("GPU RAM Free: {0:.0f}MB | Used: {1:.0f}MB | Util {2:3.0f}% | Total {3:.0f}MB".format(gpu.memoryFree, gpu.memoryUsed, gpu.memoryUtil*100, gpu.memoryTotal))
printm()

  Created wheel for gputil: filename=GPUtil-1.4.0-cp37-none-any.whl size=7411 sha256=a9de78d37a3eb4f76e1f89125c33d22cd73bdf5a761ad68ddb040033ad610b1b
  Stored in directory: /root/.cache/pip/wheels/3d/77/07/80562de4bb0786e5ea186911a2c831fdd0018bda69beab71fd
Successfully built gputil
Gen RAM Free: 12.7 GB  | Proc size: 270.3 MB
GPU RAM Free: 15106MB | Used: 3MB | Util   0% | Total 15109MB


In [2]:
device = torch.device('cuda')

In [6]:
a = torch.rand(3,3)
a

tensor([[0.1755, 0.3960, 0.8945],
        [0.0653, 0.2701, 0.7464],
        [0.5993, 0.0473, 0.1183]])

In [7]:
b = torch.rand(3,3).to(device)
b

tensor([[0.0971, 0.7842, 0.3880],
        [0.0561, 0.2479, 0.8029],
        [0.0998, 0.0979, 0.1528]], device='cuda:0')

In [13]:
c = torch.rand(3,3).cuda()
c

tensor([[0.5428, 0.8196, 0.9012],
        [0.3033, 0.3713, 0.1549],
        [0.8149, 0.0441, 0.3320]], device='cuda:0')

In [15]:
import time 

In [25]:
a = torch.ones(3000,3000)
b = torch.ones(3000,3000).cuda()
start = time.time()
for _ in range(10000):
    a+=a
duration = time.time() - start
print (duration)

start = time.time()
for _ in range(10000):
    b+=b
duration = time.time() - start
print (duration)

25.03040337562561
2.725353956222534
