<a href="https://colab.research.google.com/github/thq4n/Learn-Colab/blob/main/DLGC_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
w = torch.tensor([1], dtype=torch.float, requires_grad=True)
w

tensor([1.], requires_grad=True)

In [ ]:
def forward(x):
    return x * w

def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) ** 2 

In [ ]:
print(f'Predict from 1: {forward(1).data[0]}')

Predict from 1: 1.0


In [ ]:
my_loss = loss(1, 2)
print(my_loss)
my_loss.backward()
print(f'Gradient: 1, 2, {w.grad.data[0]}')

tensor([1.], grad_fn=<PowBackward0>)
Gradient: 1, 2, -4.0


In [ ]:
w.data = w.data - 0.1 * w.grad.data
w.grad.data.zero_()
print(w)

tensor([1.4000], requires_grad=True)
