<a href="https://colab.research.google.com/github/thq4n/Learn-Colab/blob/main/DLGC_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]], dtype = torch.float)
x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
torch.ones(1,2,dtype=torch.int)

tensor([[1, 1]], dtype=torch.int32)

In [ ]:
torch.zeros(5,2,2,dtype=torch.float)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
x = torch.rand(2,2,4,4,dtype=torch.float)
x


tensor([[[[0.6563, 0.4610, 0.9798, 0.8728],
          [0.1260, 0.0142, 0.7300, 0.4257],
          [0.6501, 0.8835, 0.3671, 0.4005],
          [0.0405, 0.5332, 0.5249, 0.8225]],

         [[0.2271, 0.4352, 0.9578, 0.9391],
          [0.8226, 0.7317, 0.0047, 0.5565],
          [0.2958, 0.4543, 0.8295, 0.9969],
          [0.7216, 0.6509, 0.4893, 0.2681]]],


        [[[0.9265, 0.2873, 0.2594, 0.8490],
          [0.4063, 0.5182, 0.2691, 0.6094],
          [0.9197, 0.6945, 0.4071, 0.1498],
          [0.0180, 0.1910, 0.6912, 0.4160]],

         [[0.6243, 0.8477, 0.7344, 0.7704],
          [0.7154, 0.6417, 0.5547, 0.5876],
          [0.8036, 0.4978, 0.1901, 0.2058],
          [0.3229, 0.1731, 0.5693, 0.1093]]]])

In [ ]:
x[:,:,:,3]

tensor([[[0.8728, 0.4257, 0.4005, 0.8225],
         [0.9391, 0.5565, 0.9969, 0.2681]],

        [[0.8490, 0.6094, 0.1498, 0.4160],
         [0.7704, 0.5876, 0.2058, 0.1093]]])

In [ ]:
x.size()

torch.Size([2, 2, 4, 4])

In [ ]:
x[0,1].size()

torch.Size([4, 4])

In [ ]:
x.size()[0]

2

In [ ]:
matrix = torch.rand(4,4)
matrix

tensor([[0.5577, 0.8344, 0.9150, 0.8782],
        [0.7246, 0.4266, 0.5599, 0.7728],
        [0.6319, 0.5342, 0.5558, 0.3884],
        [0.5150, 0.2037, 0.9612, 0.4421]])

In [ ]:
matrix.reshape(1,16)

tensor([[0.5577, 0.8344, 0.9150, 0.8782, 0.7246, 0.4266, 0.5599, 0.7728, 0.6319,
         0.5342, 0.5558, 0.3884, 0.5150, 0.2037, 0.9612, 0.4421]])

In [ ]:
matrix.reshape(-1)

tensor([0.5577, 0.8344, 0.9150, 0.8782, 0.7246, 0.4266, 0.5599, 0.7728, 0.6319,
        0.5342, 0.5558, 0.3884, 0.5150, 0.2037, 0.9612, 0.4421])

In [ ]:
torch.squeeze(matrix.reshape(1,16))

tensor([0.5577, 0.8344, 0.9150, 0.8782, 0.7246, 0.4266, 0.5599, 0.7728, 0.6319,
        0.5342, 0.5558, 0.3884, 0.5150, 0.2037, 0.9612, 0.4421])

In [ ]:
matrix.sum(0)

tensor([2.4291, 1.9990, 2.9919, 2.4816])

In [ ]:
torch.max(matrix)

tensor(0.9612)

In [ ]:
print(matrix)

tensor([[0.5577, 0.8344, 0.9150, 0.8782],
        [0.7246, 0.4266, 0.5599, 0.7728],
        [0.6319, 0.5342, 0.5558, 0.3884],
        [0.5150, 0.2037, 0.9612, 0.4421]])


In [ ]:
values, indices = torch.max(matrix, 0)
print(values)
print(indices)

tensor([0.7246, 0.8344, 0.9612, 0.8782])
tensor([1, 0, 3, 0])


In [ ]:
values, indices = torch.max(matrix, 1)
print(values)
print(indices)

tensor([0.9150, 0.7728, 0.6319, 0.9612])
tensor([2, 3, 0, 2])


In [ ]:
print(matrix[0,0])
# matrix[0,0] == 1
matrix[0,0].item()   == 1

tensor(0.5577)


False

In [ ]:
matrix.numpy()

array([[0.55766284, 0.83441675, 0.9150134 , 0.878213  ],
       [0.7245872 , 0.42655945, 0.5599177 , 0.7728359 ],
       [0.63191724, 0.5342298 , 0.55577457, 0.38842022],
       [0.5149504 , 0.20374978, 0.9612181 , 0.442096  ]], dtype=float32)

In [ ]:
import numpy as np

a = np.array([[0,1],[1,2]])
b = torch.from_numpy(a)
print(a)
print(b)

[[0 1]
 [1 2]]
tensor([[0, 1],
        [1, 2]])


In [ ]:
a[0,0] = -1
a

array([[-1,  1],
       [ 1,  2]])

In [ ]:
b

tensor([[-1,  1],
        [ 1,  2]])