<a href="https://colab.research.google.com/github/thq4n/Learn-Colab/blob/main/DLGC_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [7]:
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]], dtype = torch.float)
x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [9]:
torch.ones(1,2,dtype=torch.int)

tensor([[1, 1]], dtype=torch.int32)

In [11]:
torch.zeros(5,2,2,dtype=torch.float)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [20]:
x = torch.rand(2,2,4,4,dtype=torch.float)
x


tensor([[[[0.6563, 0.4610, 0.9798, 0.8728],
          [0.1260, 0.0142, 0.7300, 0.4257],
          [0.6501, 0.8835, 0.3671, 0.4005],
          [0.0405, 0.5332, 0.5249, 0.8225]],

         [[0.2271, 0.4352, 0.9578, 0.9391],
          [0.8226, 0.7317, 0.0047, 0.5565],
          [0.2958, 0.4543, 0.8295, 0.9969],
          [0.7216, 0.6509, 0.4893, 0.2681]]],


        [[[0.9265, 0.2873, 0.2594, 0.8490],
          [0.4063, 0.5182, 0.2691, 0.6094],
          [0.9197, 0.6945, 0.4071, 0.1498],
          [0.0180, 0.1910, 0.6912, 0.4160]],

         [[0.6243, 0.8477, 0.7344, 0.7704],
          [0.7154, 0.6417, 0.5547, 0.5876],
          [0.8036, 0.4978, 0.1901, 0.2058],
          [0.3229, 0.1731, 0.5693, 0.1093]]]])

In [26]:
x[:,:,:,3]

tensor([[[0.8728, 0.4257, 0.4005, 0.8225],
         [0.9391, 0.5565, 0.9969, 0.2681]],

        [[0.8490, 0.6094, 0.1498, 0.4160],
         [0.7704, 0.5876, 0.2058, 0.1093]]])

In [27]:
x.size()

torch.Size([2, 2, 4, 4])

In [32]:
x[0,1].size()

torch.Size([4, 4])

In [33]:
x.size()[0]

2